version: '3.8'

services:
  hadoop-master:
    image: liliasfaxi/hadoop-cluster:latest
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
      - "9092:9092"
    command: ["sh", "-c", "service ssh start && ./start-hadoop.sh &&   ./start-kafka-zookeeper.sh && while true; do sleep 1000; done"]

  hadoop-worker1:
    image: liliasfaxi/hadoop-cluster:latest
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    command: ["sh", "-c", "service ssh start && while true; do sleep 1000; done"]

  hadoop-worker2:
    image: liliasfaxi/hadoop-cluster:latest
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    command: ["sh", "-c", "service ssh start && while true; do sleep 1000; done"]

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - hadoop

#  grafana:
#    image: grafana/grafana-oss:9.2.6
#    volumes:
#      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/dashboards:/var/lib/grafana/dashboards
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
#    networks:
#      - hadoop
#    ports:
#      - "3000:3000"
#    command: ["/bin/bash", "-c", "grafana-cli plugins install hadesarchitect-cassandra-datasource"]

networks:
  hadoop:
    driver: bridge